<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\courier\TemplateCollectionInterface;
use Drupal\user\Entity\User;
use Drupal\courier\Entity\TemplateCollection;

/**
 * Implements hook_entity_access().
 */
function courier_system_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'templates' && $entity instanceof TemplateCollectionInterface) {
    // Determine if template collection belongs to courier_system.
    $template_collection_ids = \Drupal::state()->get('courier_system_template_collections', []);
    if (!$entity->isNew() && in_array($entity->id(), $template_collection_ids)) {
      return AccessResult::allowedIfHasPermission($account, 'administer account settings');
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_mail_alter().
 */
function courier_system_mail_alter(&$message) {
  $mail_id = $message['id'];
  $settings = \Drupal::config('courier_system.settings');
  $override = $settings->get('override');

  if (!empty($override[$mail_id])) {
    // Cancel sending.
    $message['send'] = FALSE;

    $template_collection_ids = \Drupal::state()->get('courier_system_template_collections', []);
    /** @var \Drupal\courier\TemplateCollectionInterface $template_collection */
    if (array_key_exists($mail_id, $template_collection_ids) && ($template_collection = TemplateCollection::load($template_collection_ids[$mail_id]))) {
      // _user_mail_notify() adds account param.
      // Only valid for user.module mails.
      /** @var \Drupal\Core\Session\AccountInterface $account */
      $account = $message['params']['account'];
      /** @var User $identity */
      $identity = User::load($account->id());
      $template_collection
        ->setTokenValue('user', $identity)
        // Required to add [user:one-time-login-url], [user:cancel-url] tokens:
        // @see user_mail_tokens().
        ->setTokenOption('callback', 'user_mail_tokens');

      /** @var \Drupal\courier\Service\CourierManagerInterface $courier_manager */
      $courier_manager = \Drupal::service('courier.manager');
      $courier_manager->sendMessage($template_collection, $identity);
    }
  }
}

